db.url=jdbc:mariadb://127.0.0.1:3306/circo_michael
db.user=root
db.password=
admin.user=admin
admin.password=admin
admin.nombre=admin
ruta.credenciales=util/credenciales.txt
ruta.espectaculos=util/espectaculos.dat
ruta.paises=src/main/resources/resources/paises.xml